INSERT INTO products (label, protein, lipid, carbohydrate, type_category, portion, label_portion, type_product, composing)
VALUES
('Pizza au pepperoni', 12.76, 32.45, 7.2, 'lipid', 150, 'g', 'entrée', '["Pâte à pizza", "sauce tomate", "fromage", "pepperoni"]'),
('Croissant au fromage', 9.65, 21.87,5.5, 'lipid', 100, 'g', 'entrée', '["Pâte feuilletée", "fromage"]'),
('Beignets de crevettes', 10.76, 28.32, 6.8, 'lipid', 120, 'g', 'entrée', '["Crevettes", "pâte à beignet"]'),
('Quiche lorraine', 11.54, 18.76, 8.2, 'lipid', 150, 'g', 'entrée', '["Pâte brisée", "oeufs", "crème fraîche", "lardons", "fromage"]'),
('Frites de patates douces', 8.32, 14.98,5.4, 'lipid', 100, 'g', 'entrée', '["Patates douces", "huile"]'),
('Ailes de poulet frites', 13.65, 25.32, 9.0, 'lipid', 120, 'g', 'entrée', '["Ailes de poulet", "farine", "assaisonnement", "huile"]'),
('Calamars frits', 12.98, 27.87, 7.5, 'lipid', 100, 'g', 'entrée', '["Calamars", "pâte à frire", "huile"]'),
('Croquettes de morue', 10.87, 23.76, 6.8, 'lipid', 100, 'g', 'entrée', '["Morue", "pommes de terre", "oeufs", "chapelure"]'),
('Chips de maïs', 9.32, 14.54,6.2, 'lipid', 50, 'g', 'entrée', '["Maïs", "huile"]'),
('Bruschetta au fromage de chèvre', 8.76, 16.98,5.6, 'lipid', 100, 'g', 'entrée', '["Pain", "fromage de chèvre", "tomates", "basilic"]'),
('Croustilles de pommes de terre', 9.87, 18.76,6.5, 'lipid', 50, 'g', 'entrée', '["Pommes de terre", "huile"]'),
('Crevettes frites', 11.98, 30.21, 7.8, 'lipid', 100, 'g', 'entrée', '["Crevettes", "pâte à frire", "huile"]'),
('Pain à l''ail', 9.54, 23.65,5.2, 'lipid', 50, 'g', 'entrée', '["Pain", "ail", "beurre", "persil"]'),
('Nachos au fromage', 11.32, 19.87, 7.0, 'lipid', 100, 'g', 'entrée', '["Nachos", "fromage"]'),
('Tempura de crevettes', 12.65, 29.32, 8.2, 'lipid', 100, 'g', 'entrée', '["Crevettes", "pâte à tempura"]'),
('Pain à la mozzarella', 10.87, 20.76, 6.0, 'lipid', 50, 'g', 'entrée', '["Pain", "mozzarella"]'),
('Croustillants au fromage', 9.76, 18.65,5.8, 'lipid', 50, 'g', 'entrée', '["Fromage", "pâte croustillante"]'),
('Cocktail de crevettes', 8.98, 19.54,5.5, 'lipid', 100, 'g', 'entrée', '["Crevettes", "sauce cocktail"]'),
('Fromage frit', 12.09, 21.32, 7.2, 'lipid', 50, 'g', 'entrée', '["Fromage", "panure"]'),
('Focaccia à l''ail et au fromage', 9.32, 17.45,5.5, 'lipid', 50, 'g', 'entrée', '["Pâte à focaccia", "ail", "fromage"]'),
('Olives marinées', 8.43, 15.76,5.0, 'lipid', 50, 'g', 'entrée', '["Olives", "huile", "herbes"]'),
('Calzones au fromage', 11.54, 19.87, 7.0, 'lipid', 100, 'g', 'entrée', '["Pâte à pizza", "fromage", "sauce tomate"]'),
('Bâtonnets de mozzarella', 12.32, 22.09, 7.5, 'lipid', 50, 'g', 'entrée', '["Mozzarella", "panure"]'),
('Tartines au fromage de chèvre', 9.87, 18.32,5.6, 'lipid', 50, 'g', 'entrée', '["Pain", "fromage de chèvre", "miel"]'),
('Ailes de poulet BBQ', 13.21, 27.76, 8.5, 'lipid', 120, 'g', 'entrée', '["Ailes de poulet", "sauce barbecue"]'),
('Tarte à la tomate et au fromage', 10.65, 16.43, 6.0, 'lipid', 100, 'g', 'entrée', '["Pâte brisée", "tomates", "fromage"]'),
('Pain à l''ail et au fromage', 11.32, 21.98, 6.5, 'lipid', 50, 'g', 'entrée', '["Pain", "ail", "fromage", "beurre"]'),
('Poulet croustillant', 12.76, 26.32, 8.0, 'lipid', 100, 'g', 'entrée', '["Poulet", "panure"]'),
('Fromage brie frit', 14.09, 23.21, 8.2, 'lipid', 50, 'g', 'entrée', '["Fromage brie", "panure"]'),
('Pain aux olives', 8.32, 14.76,5.0, 'lipid', 50, 'g', 'entrée', '["Pain", "olives", "huile"]'),
('Tacos au fromage', 9.87, 17.65,5.5, 'lipid', 100, 'g', 'entrée', '["Tortillas", "fromage", "viande hachée"]'),
('Onion rings', 11.76, 23.32, 7.0, 'lipid', 100, 'g', 'entrée', '["Oignons", "panure"]'),
('Pain à l''ail et aux herbes', 9.87, 19.54,5.4, 'lipid', 50, 'g', 'entrée', '["Pain", "ail", "herbes", "beurre"]'),
('Pain de campagne au fromage', 9.32, 15.98,5.2, 'lipid', 50, 'g', 'entrée', '["Pain de campagne", "fromage"]'),
('Boulettes de fromage frites', 13.21, 24.65, 7.8, 'lipid', 100, 'g', 'entrée', '["Fromage", "panure"]'),
('Quesadillas au fromage', 11.98, 21.32, 6.5, 'lipid', 100, 'g', 'entrée', '["Tortillas", "fromage"]'),
('Pain à l''ail et au parmesan', 10.54, 18.76, 6.0, 'lipid', 50, 'g', 'entrée', '["Pain", "ail", "parmesan", "beurre"]'),
('Nachos au fromage et à la viande', 12.43, 20.87, 7.5, 'lipid', 100, 'g', 'entrée', '["Nachos", "fromage", "viande hachée"]'),
('Beignets de calamars', 12.65, 24.09, 8.2, 'lipid', 120, 'g', 'entrée', '["Calamars", "pâte à beignet"]'),
('Pain à l''ail et au fromage bleu', 11.87, 22.54, 6.8, 'lipid', 50, 'g', 'entrée', '["Pain", "ail", "fromage bleu", "beurre"]'),
('Pain aux olives et à l''ail', 8.98, 17.76,5.2, 'lipid', 50, 'g', 'entrée', '["Pain", "olives", "ail", "beurre"]'),
('Ailes de poulet épicées', 14.21, 28.32, 9.0, 'lipid', 120, 'g', 'entrée', '["Ailes de poulet", "sauce épicée"]'),
('Pain à l''ail et au romarin', 9.65, 19.87,5.5, 'lipid', 50, 'g', 'entrée', '["Pain", "ail", "romarin", "beurre"]'),
('Pain au fromage et à l''ail', 10.54, 20.32, 6.0, 'lipid', 50, 'g', 'entrée', '["Pain", "fromage", "ail", "beurre"]'),
('Pain à l''ail et au pesto', 8.98, 16.76,5.0, 'lipid', 50, 'g', 'entrée', '["Pain", "ail", "pesto", "beurre"]'),
('Saumon rôti', 25.87, 6.12, 2.1, 'protein', 120, 'g', 'plat', '["Saumon", "huile d''olive", "sel", "poivre"]'),
('Salade de quinoa', 15.45, 2.88, 1.5, 'protein', 150, 'g', 'plat', '["Quinoa", "légumes", "vinaigrette"]'),
('Tofu sauté aux légumes', 20.76, 5.33, 1.8, 'protein', 120, 'g', 'plat', '["Tofu", "légumes", "sauce soja"]'),
('Pois chiches curry', 18.92, 4.65, 0.9, 'protein', 100, 'g', 'plat', '["Pois chiches", "curry", "légumes", "sauce tomate"]'),
('Omelette aux champignons', 18.32, 2.75, 1.2, 'protein', 120, 'g', 'plat', '["oeufs", "champignons", "herbes", "fromage"]'),
('Salade de poulet césar', 35.21, 4.92, 2.3, 'protein', 150, 'g', 'plat', '["Poulet grillé", "salade romaine", "croûtons", "sauce César"]'),
('Steak de thon grillé', 28.76, 6.84, 1.5, 'protein', 120, 'g', 'plat', '["Thon", "marinade", "citron", "sel", "poivre"]'),
('Ratatouille provençale', 12.98, 2.33, 0.5, 'protein', 150, 'g', 'plat', '["Aubergines", "courgettes", "poivrons", "tomates", "herbes de Provence"]'),
('Brochettes de légumes marinées', 8.76, 1.98, 0.3, 'protein', 100, 'g', 'plat', '["Légumes variés", "marinade", "brochettes"]'),
('Pâtes au pesto et poulet', 22.45, 5.27, 1.8, 'protein', 200, 'g', 'plat', '["Pâtes", "pesto", "poulet grillé", "fromage râpé"]'),
('Salade niçoise', 20.33, 3.92, 1.4, 'protein', 150, 'g', 'plat', '["Thon", "haricots verts", "tomates", "olives", "oeufs", "vinaigrette"]'),
('Curry de lentilles', 17.21, 3.55, 0.8, 'protein', 150, 'g', 'plat', '["Lentilles", "légumes", "curry", "lait de coco"]'),
('Filet de truite au citron', 26.87, 5.76, 1.7, 'protein', 120, 'g', 'plat', '["Truite", "citron", "herbes", "sel", "poivre"]'),
('Salade de quinoa aux légumes grillés', 18.64, 3.76, 1.2, 'protein', 150, 'g', 'plat', '["Quinoa", "légumes grillés", "vinaigrette"]'),
('Poêlée de tofu aux épices', 19.32, 4.21, 1.5, 'protein', 120, 'g', 'plat', '["Tofu", "légumes", "épices", "sauce soja"]'),
('Crevettes sautées à l''ail', 24.67, 5.89, 1.2, 'protein', 100, 'g', 'plat', '["Crevettes", "ail", "beurre", "citron"]'),
('Burger végétarien', 17.45, 3.78, 1.2, 'protein', 150, 'g', 'plat', '["Steak végétarien", "pain burger", "légumes", "sauce"]'),
('Aubergines farcies', 14.76, 2.98, 0.9, 'protein', 150, 'g', 'plat', '["Aubergines", "viande hachée", "tomates", "fromage"]'),
('Sauté de porc au miel et au gingembre', 30.21, 7.32, 2.5, 'protein', 150, 'g', 'plat', '["Porc", "miel", "gingembre", "légumes"]'),
('Salade de lentilles et de feta', 16.88, 5.45, 1.6, 'protein', 150, 'g', 'plat', '["Lentilles", "feta", "légumes", "vinaigrette"]'),
('Pâtes aux fruits de mer', 23.76, 6.45, 1.8, 'protein', 200, 'g', 'plat', '["Pâtes", "fruits de mer", "ail", "huile d''olive"]'),
('Chili végétarien', 19.54, 4.65, 1.2, 'protein', 150, 'g', 'plat', '["Haricots rouges", "légumes", "tomates", "épices"]'),
('Poulet au citron et à l''ail', 32.09, 5.98, 1.9, 'protein', 150, 'g', 'plat', '["Poulet", "citron", "ail", "herbes", "huile d''olive"]'),
('Salade de chou frisé et de poulet', 28.32, 3.76, 1.8, 'protein', 150, 'g', 'plat', '["Chou frisé", "poulet grillé", "vinaigrette", "parmesan"]'),
('Rôti de dinde aux herbes', 26.45, 6.32, 1.7, 'protein', 120, 'g', 'plat', '["Dinde", "herbes", "ail", "beurre"]'),
('Poivrons farcis au quinoa', 14.87, 3.21, 0.7, 'protein', 150, 'g', 'plat', '["Poivrons", "quinoa", "légumes", "fromage"]'),
('Poisson en papillote', 23.65, 4.98, 1.5, 'protein', 120, 'g', 'plat', '["Poisson", "légumes", "citron", "herbes"]'),
('Fajitas au poulet', 24.76, 5.65, 1.8, 'protein', 150, 'g', 'plat', '["Poulet mariné", "poivrons", "oignons", "tortillas", "guacamole"]'),
('Gratin de courgettes', 10.87, 2.54, 0.5, 'protein', 150, 'g', 'plat', '["Courgettes", "oeufs", "crème fraîche", "fromage râpé"]'),
('Tartare de saumon', 24.32, 6.43, 1.7, 'protein', 120, 'g', 'plat', '["Saumon frais", "échalotes", "câpres", "citron", "huile d''olive"]'),
('Salade de haricots verts et de crevettes', 17.65, 4.32, 1.2, 'protein', 150, 'g', 'plat', '["Haricots verts", "crevettes", "tomates", "vinaigrette"]'),
('Poulet tikka masala', 29.87, 6.98, 2.0, 'protein', 150, 'g', 'plat', '["Poulet", "sauce tikka masala", "riz", "naan"]'),
('Gratin de pommes de terre au thon', 15.76, 3.98, 1.0, 'protein', 150, 'g', 'plat', '["Pommes de terre", "thon", "crème fraîche", "fromage"]'),
('Risotto aux champignons', 13.45, 3.21, 0.8, 'protein', 200, 'g', 'plat', '["Riz", "champignons", "bouillon", "vin blanc", "parmesan"]'),
('Crevettes à la noix de coco', 27.32, 4.87, 1.6, 'protein', 100, 'g', 'plat', '["Crevettes", "noix de coco", "farine", "oeuf"]'),
('Lasagnes végétariennes', 18.65, 5.32, 1.2, 'protein', 200, 'g', 'plat', '["Légumes grillés", "pâtes à lasagnes", "sauce tomate", "béchamel", "fromage"]'),
('Boulettes de viande à la sauce tomate', 22.98, 7.21, 2.2, 'protein', 150, 'g', 'plat', '["Viande hachée", "oeufs", "parmesan", "sauce tomate"]'),
('Salade de riz aux crevettes', 20.76, 4.87, 1.4, 'protein', 150, 'g', 'plat', '["Riz", "crevettes", "légumes", "vinaigrette"]'),
('Tofu caramélisé', 17.32, 3.98, 1.1, 'protein', 120, 'g', 'plat', '["Tofu", "sauce soja", "miel", "ail", "gingembre"]'),
('Poulet au curry rouge', 31.54, 6.76, 2.1, 'protein', 150, 'g', 'plat', '["Poulet", "légumes", "curry rouge", "lait de coco"]'),
('Salade de pois chiches et de tomates', 14.87, 3.32, 0.9, 'protein', 150, 'g', 'plat', '["Pois chiches", "tomates", "concombre", "menthe", "vinaigrette"]'),
('Quiche aux épinards et au fromage de chèvre', 19.65, 5.76, 1.5, 'protein', 150, 'g', 'plat', '["oeufs", "épinards", "fromage de chèvre", "crème fraîche"]'),
('Pâtes primavera', 12.32, 2.98, 0.7, 'protein', 200, 'g', 'plat', '["Pâtes", "légumes", "ail", "huile d''olive", "parmesan"]'),
('Saumon en croûte de sésame', 26.76, 7.21, 2.0, 'protein', 120, 'g', 'plat', '["Saumon frais", "graines de sésame", "sauce soja", "miel"]'),
('Salade de pâtes au poulet', 24.09, 5.43, 1.8, 'protein', 150, 'g', 'plat', '["Pâtes", "poulet grillé", "légumes", "vinaigrette"]'),
('Ragoût de légumes d''hiver', 9.76, 2.21, 0.4, 'protein', 150, 'g', 'plat', '["Légumes d''hiver", "bouillon", "herbes", "épices"]'),
('Poulet au beurre indien', 33.21, 7.54, 2.5, 'protein', 150, 'g', 'plat', '["Poulet", "sauce au beurre", "curry", "riz", "naan"]'),
('Salade de tomates et de mozzarella', 12.87, 4.32, 1.2, 'protein', 150, 'g', 'plat', '["Tomates", "mozzarella", "basilic", "vinaigrette"]'),
('Crevettes grillées à l''ail et au citron', 26.43, 5.98, 1.5, 'protein', 100, 'g', 'plat', '["Crevettes", "ail", "citron", "huile d''olive"]'),
('Pilaf de riz aux légumes', 10.76, 2.98, 0.6, 'protein', 200, 'g', 'plat', '["Riz", "légumes", "bouillon", "épices", "herbes"]'),
('Tarte aux pommes', 6.98, 15.2, 40.76, 'carbohydrate', 150, 'g', 'dessert', '["Pâte feuilletée", "pommes", "sucre", "cannelle"]'),
('Gâteau au chocolat', 7.65, 18.5, 35.87, 'carbohydrate', 100, 'g', 'dessert', '["Chocolat noir", "beurre", "sucre", "oeufs", "farine"]'),
('Pudding à la vanille', 5.76, 22.3, 30.32, 'carbohydrate', 120, 'g', 'dessert', '["Lait", "oeufs", "sucre", "vanille", "pain rassis"]'),
('Crumble aux fruits rouges', 8.32, 16.7, 38.54, 'carbohydrate', 150, 'g', 'dessert', '["Fruits rouges", "sucre", "beurre", "farine", "flocons d''avoine"]'),
('Muffins aux myrtilles', 6.87, 19.8, 35.21, 'carbohydrate', 100, 'g', 'dessert', '["Myrtilles", "oeufs", "sucre", "beurre", "farine"]'),
('Pancakes aux pépites de chocolat', 7.43, 17.5, 32.65, 'carbohydrate', 100, 'g', 'dessert', '["Farine", "lait", "oeufs", "sucre", "pépites de chocolat"]'),
('Tiramisu', 5.98, 21.4, 29.87, 'carbohydrate', 120, 'g', 'dessert', '["oeufs", "sucre", "mascarpone", "biscuits à la cuillère", "café"]'),
('Cupcakes à la vanille', 6.76, 18.9, 34.76, 'carbohydrate', 100, 'g', 'dessert', '["Farine", "sucre", "beurre", "oeufs", "vanille"]'),
('Barres de céréales', 8.32, 20.6, 42.09, 'carbohydrate', 50, 'g', 'dessert', '["Flocons d''avoine", "miel", "fruits secs", "beurre", "sucre"]'),
('Tarte au citron meringuée', 7.21, 19.5, 36.32, 'carbohydrate', 150, 'g', 'dessert', '["Pâte sablée", "citron", "oeufs", "sucre", "beurre"]'),
('Crème brûlée', 5.43, 20.8, 28.76, 'carbohydrate', 120, 'g', 'dessert', '["oeufs", "sucre", "crème", "vanille"]'),
('Brownies au caramel', 8.76, 17.9, 38.65, 'carbohydrate', 100, 'g', 'dessert', '["Chocolat noir", "beurre", "sucre", "oeufs", "farine"]'),
('Pain perdu', 7.32, 18.2, 33.21, 'carbohydrate', 120, 'g', 'dessert', '["Pain rassis", "oeufs", "lait", "sucre", "vanille"]'),
('Glace à la vanille', 6.54, 20.5, 28.43, 'carbohydrate', 100, 'g', 'dessert', '["Crème fraîche", "lait", "sucre", "oeufs", "vanille"]'),
('Mousse au chocolat', 7.65, 19.3, 31.54, 'carbohydrate', 120, 'g', 'dessert', '["Chocolat noir", "beurre", "sucre", "oeufs"]'),
('Donuts au glaçage sucré', 9.87, 21.2, 41.32, 'carbohydrate', 100, 'g', 'dessert', '["Farine", "levure", "lait", "sucre", "oeufs"]'),
('Cookies aux pépites de chocolat', 7.98, 17.6, 40.21, 'carbohydrate', 100, 'g', 'dessert', '["Farine", "beurre", "sucre", "oeufs", "pépites de chocolat"]'),
('Panna cotta aux fruits rouges', 6.87, 18.9, 34.76, 'carbohydrate', 120, 'g', 'dessert', '["Crème", "sucre", "gélatine", "fruits rouges"]'),
('Gâteau aux carottes', 7.32, 18.4, 35.98, 'carbohydrate', 150, 'g', 'dessert', '["Carottes râpées", "farine", "sucre", "oeufs", "huile"]'),
('Tartelette aux fraises', 8.32, 16.8, 37.65, 'carbohydrate', 100, 'g', 'dessert', '["Pâte sablée", "fraises", "sucre", "gelée de fruits"]'),
('Cheesecake aux fruits de la passion', 6.98, 20.2, 32.76, 'carbohydrate', 120, 'g', 'dessert', '["Biscuits émiettés", "fromage frais", "fruits de la passion", "sucre"]'),
('Barres énergétiques aux noix', 8.65, 19.3, 39.54, 'carbohydrate', 50, 'g', 'dessert', '["Flocons d''avoine", "miel", "fruits secs", "noix", "beurre"]'),
('Soufflé au chocolat', 7.76, 18.7, 33.32, 'carbohydrate', 120, 'g', 'dessert', '["Chocolat noir", "beurre", "sucre", "oeufs"]'),
('Cannelés bordelais', 8.98, 21.5, 42.21, 'carbohydrate', 100, 'g', 'dessert', '["Farine", "sucre", "oeufs", "lait", "rhum"]'),
('Gaufres aux fraises', 7.87, 18.2, 36.43, 'carbohydrate', 100, 'g', 'dessert', '["Farine", "lait", "oeufs", "sucre", "beurre"]'),
('Pain d''épices', 8.54, 19.6, 37.21, 'carbohydrate', 100, 'g', 'dessert', '["Farine", "miel", "sucre", "oeufs", "épices"]'),
('Crêpes au Nutella', 8.32, 20.8, 39.76, 'carbohydrate', 100, 'g', 'dessert', '["Farine", "lait", "oeufs", "sucre", "Nutella"]'),
('Pudding au pain', 6.76, 18.9, 31.87, 'carbohydrate', 120, 'g', 'dessert', '["Pain rassis", "lait", "oeufs", "sucre", "vanille"]'),
('Mille-feuille à la vanille', 7.21, 19.3, 34.32, 'carbohydrate', 100, 'g', 'dessert', '["Pâte feuilletée", "crème pâtissière", "sucre glace", "vanille"]'),
('Barres de chocolat au riz soufflé', 9.65, 22.4, 45.21, 'carbohydrate', 50, 'g', 'dessert', '["Chocolat noir", "riz soufflé", "beurre", "sucre", "oeufs"]'),
('Tartelette au citron', 8.32, 17.8, 36.54, 'carbohydrate', 100, 'g', 'dessert', '["Pâte sablée", "citron", "oeufs", "sucre", "beurre"]'),
('Beignets aux pommes', 8.09, 17.5, 34.76, 'carbohydrate', 100, 'g', 'dessert', '["Pâte à beignets", "pommes", "sucre", "cannelle"]'),
('Pudding au riz', 7.32, 19.1, 32.43, 'carbohydrate', 120, 'g', 'dessert', '["Riz", "lait", "sucre", "vanille", "oeufs"]'),
('Gâteau à la banane', 7.65, 18.3, 34.87, 'carbohydrate', 100, 'g', 'dessert', '["Bananes écrasées", "farine", "sucre", "oeufs", "beurre"]'),
('Muffins aux pépites de chocolat', 7.43, 19.2, 36.32, 'carbohydrate', 100, 'g', 'dessert', '["Farine", "oeufs", "sucre", "pépites de chocolat", "beurre"]'),
('Pain aux raisins', 8.76, 18.8, 40.65, 'carbohydrate', 100, 'g', 'dessert', '["Pâte levée", "raisins secs", "sucre", "beurre", "oeufs"]'),
('Tarte aux fraises', 8.09, 17.6, 38.32, 'carbohydrate', 100, 'g', 'dessert', '["Pâte sablée", "crème pâtissière", "fraises", "gelée de fruits"]'),
('Coulant au chocolat', 7.54, 18.9, 34.21, 'carbohydrate', 100, 'g', 'dessert', '["Chocolat noir", "beurre", "sucre", "oeufs", "farine"]'),
('Gâteau au fromage à la framboise', 7.32, 19.5, 33.76, 'carbohydrate', 100, 'g', 'dessert', '["Biscuits émiettés", "fromage frais", "framboises", "sucre"]'),
('Mousse à la mangue', 6.76, 20.1, 31.43, 'carbohydrate', 120, 'g', 'dessert', '["Mangue", "yaourt", "sucre", "gélatine"]'),
('Pain au chocolat', 8.43, 18.4, 36.76, 'carbohydrate', 100, 'g', 'dessert', '["Pâte levée feuilletée", "chocolat", "sucre"]'),
('Clafoutis aux cerises', 8.65, 17.9, 37.32, 'carbohydrate', 100, 'g', 'dessert', '["Cerises", "oeufs", "farine", "sucre", "lait"]'),
('Flan aux oeufs', 7.21, 19.3, 31.65, 'carbohydrate', 120, 'g', 'dessert', '["oeufs", "lait", "sucre", "vanille"]'),
('Gâteau au yaourt', 7.54, 18.7, 35.09, 'carbohydrate', 100, 'g', 'dessert', '["Yaourt", "oeufs", "farine", "sucre", "huile"]'),
('Tarte aux abricots', 8.32, 17.7, 38.54, 'carbohydrate', 100, 'g', 'dessert', '["Pâte sablée", "abricots", "sucre", "amandes"]');
